# Generated by Django 5.0.6 on 2026-05-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciselog',
            name='calories_burned',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
